name: gg_once_per_cycle
description: Use GgOncePerCycle to trigger tasks multiple times while ensuring they are only executed one time during a run loop cycle.
version: 0.0.1+3
homepage: https://github.com/inlavigo/gg_once_per_cycle

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  fake_async: ^1.1.0
